package cc.meteormc.xposedkit.plugin.task

import cc.meteormc.xposedkit.plugin.util.Metadata
import cc.meteormc.xposedkit.plugin.util.XmlUtil
import org.gradle.api.file.Directory
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import java.io.File
import java.util.Properties
import javax.xml.stream.XMLStreamConstants
import kotlin.math.max

abstract class GenerateResourcesTask : BaseTask() {
    companion object {
        private const val SCOPES_RESOURCE_NAME = "module_scopes"
    }

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val staticRes: ListProperty<Directory>

    @get:OutputDirectory
    abstract val output: DirectoryProperty

    override fun execute() {
        val metadata = parseMetadata()

        resolveFile("META-INF/xposed/module.prop").bufferedWriter().use {
            Properties().apply {
                setProperty("minApiVersion", max(100, metadata.getProperty(Metadata.MIN_API).toInt()).toString())
                setProperty("targetApiVersion", max(100, metadata.getProperty(Metadata.TARGET_API).toInt()).toString())
                setProperty("staticScope", metadata.getProperty(Metadata.STATIC_SCOPE))
                setProperty("autoHotReload", metadata.getProperty(Metadata.AUTO_HOT_RELOAD))
            }.store(
                it,
                "Automatically generated by XposedKit"
            )
        }

        resolveFile("META-INF/xposed/scope.list").bufferedWriter().use {
            scanScopes().forEach { scope ->
                if (scope.isBlank()) return@forEach
                it.write(scope)
                it.newLine()
            }
        }
    }

    fun scanScopes(): List<String> {
        return staticRes.get().map {
            it.dir("values").asFileTree.mapNotNull { file ->
                val result = mutableListOf<String>()
                val reader = XmlUtil.createXMLReader(file)
                while (reader.hasNext()) {
                    if (reader.next() != XMLStreamConstants.START_ELEMENT) continue
                    if (reader.localName != "string-array") continue
                    if (reader.getAttributeValue(null, "name") != SCOPES_RESOURCE_NAME) continue
                    while (reader.hasNext()) {
                        when (reader.next()) {
                            XMLStreamConstants.START_ELEMENT -> {
                                if (reader.localName != "item") continue
                                result += reader.elementText
                            }
                            XMLStreamConstants.END_ELEMENT -> {
                                if (reader.localName != "string-array") continue
                                return@map result
                            }
                        }
                    }
                }

                null
            }
        }.flatten()
    }

    private fun resolveFile(path: String): File {
        return output.file(path)
            .get()
            .asFile
            .apply { parentFile.mkdirs() }
    }
}