package cc.meteormc.xposedkit.plugin.task

import cc.meteormc.xposedkit.plugin.util.Metadata
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.OutputDirectory
import java.util.Properties
import kotlin.math.max

abstract class GenerateResourcesTask : BaseTask() {
    @get:OutputDirectory
    abstract val output: DirectoryProperty

    override fun execute() {
        val metadata = parseMetadata()

        Properties().apply {
            setProperty("minApiVersion", max(100, metadata.getProperty(Metadata.MIN_API).toInt()).toString())
            setProperty("targetApiVersion", max(100, metadata.getProperty(Metadata.TARGET_API).toInt()).toString())
            setProperty("staticScope", metadata.getProperty(Metadata.STATIC_SCOPE))
            setProperty("autoHotReload", metadata.getProperty(Metadata.AUTO_HOT_RELOAD))
        }.store(
            output.file("META-INF/xposed/module.prop")
                .get()
                .asFile
                .apply { parentFile.mkdirs() }
                .bufferedWriter(),
            "Automatically generated by XposedKit"
        )
    }
}