# For more information about using CMake with Android Studio, read the
# documentation: https://d.android.com/studio/projects/add-native-code.html.
# For more examples on how to use CMake, see https://github.com/android/ndk-samples.

cmake_minimum_required(VERSION 3.28)
project(xposedkit LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_SCAN_FOR_MODULES ON)

file(GLOB_RECURSE XPOSEDKIT_SRC_FILES CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/*.cxx)

add_library(${CMAKE_PROJECT_NAME} SHARED)
target_sources(${CMAKE_PROJECT_NAME} PRIVATE
        FILE_SET CXX_MODULES
        FILES ${XPOSEDKIT_SRC_FILES}
)

add_subdirectory(external/openjdkjvmti)
add_subdirectory(external/xdl)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
        openjdkjvmti_headers
        xdl
)

target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE
        ${CMAKE_CURRENT_SOURCE_DIR}/include
)